<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-EventDriven.Consumer.Worker-07524ab1-7f9d-4643-8fc8-e9268daedcf0</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
		<PackageReference Include="OpenTelemetry" Version="1.17.0" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.17.0" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />		
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EventDriven.Contracts\EventDriven.Contracts.csproj" />
		<ProjectReference Include="..\EventDriven.Publisher.Api\EventDriven.Publisher.Api.csproj" />
		<ProjectReference Include="..\EventDriven.ServiceDefaults\EventDriven.ServiceDefaults.csproj" />
	</ItemGroup>
</Project>
